export const GET_USER_PENDING='GET_USER_PENDING';
export const GET_USER_SUCCESS='GET_USER_SUCCESS';
export const GET_USER_ERROR='GET_USER_ERROR';

export const GET_TASK_SUCCESS='GET_TASK_SUCCESS';
export const GET_TASK_ERROR='GET_TASK_ERROR';

export const GET_BLOG_SUCCESS='GET_BLOG_SUCCESS';
export const GET_BLOG_ERROR='GET_BLOG_ERROR';

export const UPDATE_DETAIL='UPDATE_DETAIL';